---

- name: Install DevSpaces Operator Subscription
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: devspaces
        namespace: openshift-operators
      spec:
        channel: stable
        name: devspaces
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        installPlanApproval: Automatic

- name: Check if DevSpaces CRD is available
  command: oc get crd checlusters.org.eclipse.che 
  register: crd_status
  retries: 20
  delay: 5
  until: crd_status.rc == 0

- name: Create openshift-workspaces Namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        name: openshift-workspaces
      spec:

- name: Wait for DevSpaces API to become available
  ansible.builtin.pause:
    minutes: 1      

- name: Install Devspaces Instance
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: org.eclipse.che/v2
      kind: CheCluster
      metadata:
        name: devspaces
        namespace: openshift-workspaces
      spec:        